---
version: '3'
services:
  influxdb:
    image: influxdb:2.3.0
    volumes:
      - $PWD/data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
      DOCKER_INFLUXDB_INIT_ORG: sda
      DOCKER_INFLUXDB_INIT_BUCKET: training
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: sda-token
    ports:
      - "8086:8086"

  notebook:
    image: jupyter/pyspark-notebook:67b8fb91f950
    ports:
      - 8889:8888
    volumes:
      - ./datagen:/home/jovyan/work
    environment:
        - GRANT_SUDO=yes
        - JUPYTER_ENABLE_LAB=yes
        - JUPYTER_TOKEN=sda
